"""Supported football competitions. Provider IDs are distinct from ESPN slugs.

ESPN slugs checked against its soccer catalogue and Brazilian league dropdown.
Football-Data codes checked against /v4/competitions and its free coverage list.
Only mapped competitions are offered for each optional provider.
"""

LEAGUES = {
    'bra.1': 'Brasileirão Série A',
    'bra.2': 'Brasileirão Série B',
    'bra.3': 'Brasileirão Série C',
    'bra.copa_do_brazil': 'Copa do Brasil',
    'bra.copa_do_nordeste': 'Copa do Nordeste',
    'bra.supercopa_do_brazil': 'Supercopa do Brasil',
    'bra.camp.paulista': 'Campeonato Paulista',
    'bra.camp.carioca': 'Campeonato Carioca',
    'bra.camp.gaucho': 'Campeonato Gaúcho',
    'bra.camp.mineiro': 'Campeonato Mineiro',
    'bra.saopaulo_youth_cup': 'Copinha · Copa São Paulo',
    'bra.brasileiro_u20': 'Brasileirão Sub-20',
    'conmebol.libertadores': 'Libertadores',
    'conmebol.sudamericana': 'Copa Sul-Americana',
    'conmebol.recopa': 'Recopa Sul-Americana',
    'eng.1': 'Premier League',
    'eng.2': 'Championship · Inglaterra',
    'eng.fa': 'Copa da Inglaterra · FA Cup',
    'eng.league_cup': 'Copa da Liga Inglesa',
    'esp.1': 'La Liga',
    'esp.2': 'Campeonato Espanhol · Segunda Divisão',
    'esp.copa_del_rey': 'Copa do Rei · Espanha',
    'ger.1': 'Bundesliga · Alemanha',
    'ger.2': '2. Bundesliga · Alemanha',
    'ger.dfb_pokal': 'Copa da Alemanha',
    'ita.1': 'Campeonato Italiano · Serie A',
    'ita.2': 'Campeonato Italiano · Serie B',
    'ita.coppa_italia': 'Copa da Itália',
    'fra.1': 'Ligue 1 · França',
    'fra.2': 'Ligue 2 · França',
    'fra.coupe_de_france': 'Copa da França',
    'por.1': 'Liga Portuguesa · Primeira Liga',
    'ned.1': 'Eredivisie · Países Baixos',
    'sco.1': 'Campeonato Escocês',
    'bel.1': 'Campeonato Belga',
    'tur.1': 'Campeonato Turco',
    'uefa.champions': 'Champions League',
    'uefa.europa': 'Europa League',
    'uefa.europa.conf': 'Conference League',
    'arg.1': 'Campeonato Argentino',
    'arg.copa': 'Copa Argentina',
    'chi.1': 'Campeonato Chileno',
    'uru.1': 'Campeonato Uruguaio',
    'col.1': 'Campeonato Colombiano',
    'per.1': 'Campeonato Peruano',
    'ecu.1': 'Campeonato Equatoriano',
    'par.1': 'Campeonato Paraguaio',
    'usa.1': 'MLS · Estados Unidos e Canadá',
    'mex.1': 'Liga MX · México',
    'jpn.1': 'Campeonato Japonês · J1 League',
    'aus.1': 'Campeonato Australiano · A-League',
    'chn.1': 'Campeonato Chinês',
    'ksa.1': 'Campeonato Saudita',
    'fifa.friendly': 'Amistosos de seleções',
    'fifa.world': 'Copa do Mundo',
    'uefa.euro': 'Eurocopa',
    'uefa.nations': 'Liga das Nações da UEFA',
    'conmebol.america': 'Copa América',
    'caf.nations': 'Copa Africana de Nações',
    'fifa.worldq.conmebol': 'Eliminatórias da Copa · América do Sul',
    'fifa.worldq.uefa': 'Eliminatórias da Copa · Europa',
    'fifa.wwc': 'Copa do Mundo Feminina',
    'uefa.wchampions': 'Champions League Feminina',
    'eng.w.1': 'Superliga Feminina · Inglaterra',
    'usa.nwsl': 'NWSL · Estados Unidos · Feminino',
}

LEAGUE_IDS = {
    'api_football': {
        'bra.1': '71', 'bra.2': '72', 'bra.copa_do_brazil': '73',
        'conmebol.libertadores': '13', 'eng.1': '39', 'esp.1': '140', 'uefa.champions': '2',
    },
    'football_data': {
        'bra.1': 'BSA', 'eng.1': 'PL', 'eng.2': 'ELC', 'esp.1': 'PD',
        'ger.1': 'BL1', 'ita.1': 'SA', 'fra.1': 'FL1', 'por.1': 'PPL', 'ned.1': 'DED',
        'uefa.champions': 'CL', 'uefa.euro': 'EC', 'fifa.world': 'WC',
    },
    'thesportsdb': {
        'bra.1': '4351', 'eng.1': '4328', 'eng.2': '4329', 'sco.1': '4330',
        'ger.1': '4331', 'ita.1': '4332', 'esp.1': '4335',
        'uefa.champions': '4480', 'conmebol.libertadores': '4501',
    },
}
